os: linux
language: perl
services:
  - rabbitmq
env:
  - "HARNESS_OPTIONS=j9 HARNESS_VERBOSE=1 TEST_POD=1"
install:
  - cpanm --quiet --notest --skip-satisfied Module::Build::Tiny
  - cpanm -n --installdeps .
sudo: false
notifications:
  email: false
matrix:
  include:
    - dist: trusty
      perl:
        - "5.28"
        - "5.26"
        - "5.24"
        - "5.22"
        - "5.20"
        - "5.18"
        - "5.16"
        - "5.14"
        - "5.12"
    - dist: xenial
      perl:
        - "5.28"
        - "5.26"
        - "5.24"
        - "5.22"
